### ISSUE TITLE
有下载下来可以运行的吗

### ISSUE THREAD

**Issue by boycehe** [febobo/react-native-redux-FeInn#16]
这边按照步骤 下载下来运行报
<img width="313" alt="2016-06-16 6 29 04" src="https://cloud.githubusercontent.com/assets/4113141/16113748/3d551646-33f0-11e6-9f38-8222d6c0996a.png">
这类车错误很多。。。

**Comment by febobo** [comment]
你手动npm install redux-actions --save 一下， 这边可能忘写package了
