### ISSUE TITLE
文件大小写问题

### ISSUE THREAD

**Issue by jiangli373** [febobo/react-native-redux-FeInn#23]
reducers目录下除了index.js以后的其它几个文件导入actions/actionTypes大小写问题

例如:src/reducers/Essence.js 
导入了actions/actionTypes

`import * as types from '../actions/actionTypes';`

但是src/actions/ActionTypes.js 这个文件是大写的

所以clone下代码，执行的时候会报错，显示找不到这个文件

![image](https://cloud.githubusercontent.com/assets/1632862/16187080/e303d5ec-3700-11e6-846e-9d35659c4670.png)

**Comment by febobo** [comment]
奇怪， 没道理啊， 在我这是小写的
![image](https://cloud.githubusercontent.com/assets/9276376/16188778/cf856cc0-3709-11e6-9f3a-078a692be3ce.png)

你那边现在能跑起来吗 ？

**Comment by jiangli373** [comment]
跑步起来，需要该文件名字的大小写才可以

![image](https://cloud.githubusercontent.com/assets/1632862/16188917/7b8b0426-370a-11e6-8121-df749383f24e.png)

是不是mac下不区分文件的大小写的问题呢，然后git的话，需要设置下对文件大小写敏感

**Comment by jiangli373** [comment]
我看提交记录，好像是一开始这个文件开头字母就是大写的，然后后来你本地好像是改成小写了吧，然后mac不区分文件大小写，git提交的时候并没有更新文件的名字造成的

**Comment by febobo** [comment]
应该是如你所说
