### ISSUE TITLE
could not connect to development server

### ISSUE THREAD

**Issue by NextZeus** [febobo/react-native-redux-FeInn#26]
使用Xcode 7 run FeInn.xcodeproj, 结果timeout 。
错误内容：
could not connect to development server
Ensure the following:
Node server is running and avaliable on the same network- run 'npm start' from react-native root
Node server URL is correctly set in AppDelegate

**Comment by febobo** [comment]
![image](https://cloud.githubusercontent.com/assets/9276376/16253047/c16a2484-3865-11e6-816c-bed4558d42ab.png)
确保这几步都做了吗 ？ 你的server 没起来， try ```$ npm start```

**Comment by NextZeus** [comment]
npm start 已经运行起来了 。

**Comment by febobo** [comment]
把AppDelegate.m 里面的ip 换成你自己的， 另外socket 也换成你自己的ip

**Comment by NextZeus** [comment]
现在我的问题变成了 https://github.com/facebook/react-native/issues/4968 这个 醉了

**Comment by febobo** [comment]
能不能贴个具体的错误出来 ？

**Comment by NextZeus** [comment]
jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];

我改成了localhost， 刚开始的问题是这样解决的。

现在的问题报错如下图：
![image](https://cloud.githubusercontent.com/assets/10203487/16288264/a685d21e-391c-11e6-8d51-d80aa3f34efa.png)

![image](https://cloud.githubusercontent.com/assets/10203487/16288282/cc37a712-391c-11e6-8b0e-42ed64fe1444.png)

**Comment by NextZeus** [comment]
[8:34:13 AM] <START> request:/index.ios.bundle?platform=ios&dev=true
[8:34:13 AM] <START> find dependencies
transformed 735/749 (98%)

这是服务器端的log 应该是接收到请求了

**Comment by febobo** [comment]
![image](https://cloud.githubusercontent.com/assets/9276376/16290412/a6fe857a-392f-11e6-9dc0-2dbad5f9d006.png)
你把这个文件的ActionType 改为actionType 就好了 具体见[23](https://github.com/febobo/react-native-redux-FeInn/issues/23#issuecomment-227091530)

**Comment by NextZeus** [comment]
大小写的问题修改文件名actionTypes.js解决了。 又出来个新问题
![image](https://cloud.githubusercontent.com/assets/10203487/16291821/99a4ec12-393d-11e6-8c35-acd1674480e0.png)

**Comment by NextZeus** [comment]
我手动安装了一下 npm install util --save 可以运行了。 谢谢febobo的指导 ！

**Comment by febobo** [comment]
客气，共同学习， 有问题欢迎随时issue
