### ISSUE TITLE
FeInn-v0.0.5 检出运行报错

### ISSUE THREAD

**Issue by doudadou** [febobo/react-native-redux-FeInn#35]
**FeInn-v0.0.5** 检出 首次 `react-native run-ios` **运行后报错，环境为0.0.5** package环境

![image](https://cloud.githubusercontent.com/assets/1428583/16368367/39d392b8-3c60-11e6-9cc9-65e04187ac13.png)

**Comment by febobo** [comment]
见 [issue23](https://github.com/febobo/react-native-redux-FeInn/issues/23)

**Comment by doudadou** [comment]
的确是
