### ISSUE TITLE
JSON value '<null>' of type NSNull cannot be converted to NSString

### ISSUE THREAD

**Issue by doudadou** [febobo/react-native-redux-FeInn#38]
![image](https://cloud.githubusercontent.com/assets/1428583/16406893/6a2f4dd8-3d43-11e6-9728-9760c02fa57f.png)
FeInn-v0.0.5 (0.28.0环境)首页初次加载报错上述错误，Hot Reload刷新后，报错消失

**Comment by febobo** [comment]
这个好像是Image url 为空造成的 ，dismiss 后并不会影响正常流程 ， 我在Feinn 没遇到这种问题 ， 在工作中遇到过 ， 直接dismiss了 。。

**Comment by doudadou** [comment]
运行你的0.25环境是没有这问题，那我也暂时dismiss了先。。。
