### ISSUE TITLE
npm install 之后，提示找不到文件目录。

### ISSUE THREAD

**Issue by devyu** [febobo/react-native-redux-FeInn#43]
不知道为什么，github上传图片总是失败，无法上传截图。npm install 之后提示： Unable to find this modules directories under /Users/mac/Desktop/react-native-redux-FeInn/src/actions/actionTypes and its parent directories. 我检查了一下，没找到有错误的引用文件。摘录出 package.js 中配置信息：

`"react": "^15.1.0",
 15     "react-native": "^0.28.0",`

不知道你那里有没有这个问题？

**Comment by febobo** [comment]
详见[23](https://github.com/febobo/react-native-redux-FeInn/issues/23)
