### ISSUE TITLE
ios xcode run 后出现Cannot read property 'Aspect' of undefined

### ISSUE THREAD

**Issue by tungh** [febobo/react-native-redux-FeInn#44]
npm start后，用xcode打开 run后 出现下面错误

Cannot read property 'Aspect' of undefined

**Comment by febobo** [comment]
截图然后  ctrl+v 粘贴 ， 看上面的这个platform 应该不会影响流程的 ， 你目前用的哪个一个分支

**Comment by tungh** [comment]
0.1.1最新分支
![image](https://cloud.githubusercontent.com/assets/3821983/16680227/bb125e5a-451f-11e6-8b76-fc486158d7c4.png)

**Comment by tungh** [comment]
![image](https://cloud.githubusercontent.com/assets/3821983/16680239/d7831b4c-451f-11e6-9ce9-246fc4f0c48c.png)

**Comment by febobo** [comment]
以后有问题先搜下issue ， 这个问题见[29](https://github.com/febobo/react-native-redux-FeInn/issues/29)

**Comment by tungh** [comment]
上面29是我粗心了，没仔细看。。。感谢~
rnpm后出现新问题
![image](https://cloud.githubusercontent.com/assets/3821983/16684267/c0523cb6-4536-11e6-91cc-42d480864d5e.png)

**Comment by febobo** [comment]
wechat 这个需要手动配置一点东西，[wechat doc](https://github.com/weflex/react-native-wechat)
