### ISSUE TITLE
RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by NexusLee** [febobo/react-native-redux-FeInn#46]

**Comment by febobo** [comment]
happen to what branch, Do you can give me the wrong address and error screenshot

**Comment by NexusLee** [comment]
@febobo 
![1f58265e-5af1-4504-997d-bd3292cdd51d](https://cloud.githubusercontent.com/assets/4703440/17126545/b75cab3e-5330-11e6-9049-8d73793549cd.png)

**Comment by febobo** [comment]
@NexusLee  
try change RCTWebChat.xcodeproj → Build Settings → Search Paths → Header Search Paths to
$(SRCROOT)/../../react-native/React and
$(SRCROOT)/../../react-native/Libraries
https://github.com/weflex/react-native-wechat/issues/33

**Comment by NexusLee** [comment]
It worked. Thx
