### ISSUE TITLE
好卡

### ISSUE THREAD

**Issue by 471685249** [febobo/react-native-redux-FeInn#49]
问题不少，签名文件报错，文件大小写错误，各种比列表数据还多的警告。。。

**Comment by 471685249** [comment]
分享modal弹出，按返回直接退出应用

**Comment by 471685249** [comment]
额。。。压根就没做返回处理。。。

**Comment by 471685249** [comment]
点开福利发现每秒消耗流量3M+。。。。

**Comment by 471685249** [comment]
已没有勇气再次打开。。。直接看代码。。

**Comment by febobo** [comment]
谢谢反溃，如题只是一个学习的demo，线上环境并不达标，如有兴趣， 欢迎pr过来 ，哈哈哈，你最后一句逗死我了 。。。。你是在打包一个装到手机了 ？

**Comment by febobo** [comment]
至于你说卡的问题，应该就是视频跟图片那块，那块目前是没有做任何优化的

**Comment by 471685249** [comment]
redux用的不错

**Comment by febobo** [comment]
有问题还请多反溃 ＊_＊
