### ISSUE TITLE
Navigator跳转卡顿

### ISSUE THREAD

**Issue by jiangli373** [febobo/react-native-redux-FeInn#5]
页面的跳转方式，我改成了从右边滑进来
Navigator.SceneConfigs.FloatFromRight;

然后页面跳转的时候，很卡，最后的页面有时会出现截图2里面的效果

![image](https://cloud.githubusercontent.com/assets/1632862/15812294/deb38db4-2be5-11e6-9a13-0076ba81d44a.png)

![image](https://cloud.githubusercontent.com/assets/1632862/15812296/e4d4343c-2be5-11e6-99bb-2701ad1af575.png)

**Comment by febobo** [comment]
我这边没法复现这个问题， 你重新pull 一次代码试下

**Comment by jiangli373** [comment]
![843b66bfdf418bdb73f9af8c54115b8a](https://cloud.githubusercontent.com/assets/1632862/15812719/d70eef90-2bea-11e6-8a32-d7f17f7fac3b.png)

这个是我用最新的代码运行出来的效果，就是页面跳转的时候，感觉卡，尤其是下面的tab条

**Comment by febobo** [comment]
(http://facebook.github.io/react-native/docs/performance.html)[http://facebook.github.io/react-native/docs/performance.html]   开发模式下navigator 表现应该就是这样的 ， 打包好就没了
