### ISSUE TITLE
 建议在readme中写一下详细的运行过程

### ISSUE THREAD

**Issue by light-of-king** [febobo/react-native-redux-FeInn#50]
这个项目有些问题一直没更新，建议直接在readme中说明下，我也是搞了一个小时才搞定问题，运行起来的。
--文件大小写问题
    src/action/ActionTypes.js 更改为 actionTypes.js
--npm版本问题
    升级了npm到最新版本
--react-native版本问题
    升级react-native到0.32
--Xcode8beta运行报错修改问题
    定义返回值为 int a,后面添加 a=0即可

**Comment by febobo** [comment]
嗯， 由于个人时间上的问题，再加上项目本身意义在于提供学习交流，故近期没有花心思维护， 如果可以， 欢迎提pr ， thx
