### ISSUE TITLE
unalble to find this module in its module map or nay of the node_modules directories

### ISSUE THREAD

**Issue by leinov** [febobo/react-native-redux-FeInn#53]
编译成功 但是报错：unable to resolve module../actions/actionTypes from /Users/leinov/webserver/github/react-native-redux-Felnn/src/reduceers/Essence.js:unalble to find this module in its module map or nay of the node_modules directories under /...

**Comment by leinov** [comment]
好了 您的js命名是ActionTypes import的是actionTypes 改成大写的就好了

**Comment by febobo** [comment]
谢谢，反溃

**Comment by leinov** [comment]
是不是你设置大小写什么了 好多提示you are manually calling a react.proptypes validation function for the flex props

**Comment by leinov** [comment]
you are manually calling a react.proptypes validation function for the 'borderStyle' props 所有的css都提示了

**Comment by febobo** [comment]
没有吧 ？可能是版本变化太快 ，有些废弃了吧 ？
