### ISSUE TITLE
XCode8跑不起来

### ISSUE THREAD

**Issue by mengerpiao** [febobo/react-native-redux-FeInn#54]
1.
Undefined symbols for architecture x86_64:
  "_RCTIsMainQueue", referenced from:
      -[RCTModuleData setUpInstanceAndBridge] in libReact.a(RCTModuleData.o)
      -[RCTModuleData instance] in libReact.a(RCTModuleData.o)
      -[RCTModuleData gatherConstants] in libReact.a(RCTModuleData.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

2.微信的API有废弃的需要更改。

**Comment by febobo** [comment]
欢迎提pr 过来

**Comment by linchanglin** [comment]
xcode8 跑不起来什么原因啊

**Comment by febobo** [comment]
https://github.com/febobo/react-native-redux-FeInn/issues/57
