### ISSUE TITLE
关于注释的问题

### ISSUE THREAD

**Issue by salmon002** [febobo/react-native-redux-FeInn#63]
感觉少一些注释跟说明性的东西， 全是代码？ 后期会添加吗？

**Comment by febobo** [comment]
额， 基本上都是业务代码，所以感觉写注释的意义不大， 个人觉得认真读一次代码比看注释的收获应该要大一点

**Comment by salmon002** [comment]
我看到0.0.1将代码更新到 rn 0.41， 其他的分支有计划更新吗？ 貌似好多代码得写法比较老了，期待。
